---
name: Go test

on:
  push:
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        name: checkout
        with:
          persist-credentials: false

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        name: setup go
        with:
          go-version-file: "go.mod"
          cache: true

      - run: make lint
        name: make lint

      - run: make testrace
        name: make testrace

      - run: make testcover
        name: make testcover

      - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
