---
name: Go test

on:
  push:
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        name: checkout
        with:
          persist-credentials: false

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        name: setup go
        with:
          go-version-file: "go.mod"
          cache: true

      - run: make lint
        name: make lint
        # Tests are run on Linux using make testcover
        if: matrix.os != 'ubuntu-latest'

      - run: make test
        name: make test
        # Tests are run on Linux using make testcover
        if: matrix.os != 'ubuntu-latest'

      - run: make testrace
        name: make testrace
        if: matrix.os == 'ubuntu-latest'

      - run: make testcover
        name: make testcover
        if: matrix.os == 'ubuntu-latest'

      - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        if: matrix.os == 'ubuntu-latest' && github.event_name != 'merge_group'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
